Fixed README to reflect current column names
I've got error which is very confusing to start with:

```
ERROR:  unrecognized/invalid column "k" for foreign table "tatoos"
```